[tools]
rust = "1.75"

[env]
_.file = '.env'
"RUST_LOG" = "debug"

[tasks.cli]
dir = "crates/key"
run = "cargo run --bin key"

[tasks.app]
dir = "crates/ui"
run = "cargo run"

[tasks."cli:build"]
dir = "crates/key"
run = "cargo build --bin key --release"

[tasks."cli:install"]
depends = ["cli:build"]
run = "cp target/release/key $HOME/bin/key"
