[tools]
rust = "1.75"
bun = "1.1"

[env]
_.file = '.env'
# "RUST_LOG" = "debug"

[tasks.cli]
dir = "key"
run = "cargo run --bin key"

[tasks."cli:build"]
dir = "key"
run = "cargo build --bin key --release"

[tasks."cli:install"]
depends = ["cli:build"]
run = "cp target/release/key $HOME/bin/key"

[tasks.app]
dir = "./"
run = "mise run ui:dev ::: app:dev"

[tasks."ui:dev"]
dir = "ui"
run = "bun i && bun run dev"

[tasks."app:dev"]
dir = "app"
run = "cargo tauri dev"

[tasks.raycast]
dir = "raycast/key"
run = "bun i && bun run dev"

[tasks."wasm:build"]
dir = "key"
run = "wasm-pack build --release"
